---
title: "Relatório"
author: "Pedro"
date: "2022-12-28"
output: html_document
---

```{r setup, include=FALSE}
library(dunn.test)
setwd("/home/uff/Área de Trabalho/arquivos/lorena/dados_solo")
df <- read.csv("dados_solo.txt", h=T, sep="\t")
df$Áreas <- as.factor(df$Áreas)
df$Prof <- as.factor(df$Prof)
df$Coleta <- as.factor(df$Coleta)
```

## Shapiro Test (dados não paramétricos)
```{r, fig.width=15, fig.height=10, echo=FALSE}
par(mfrow=c(4,5))

for (col in 4:ncol(df)) {
  print(paste(names(df)[col]))
  print(shapiro.test(df[,col]))
  qqnorm(df[,col], main=paste(names(df)[col]))
  qqline(df[,col], col="red")
}
```

## Boxplot e testes
```{r, fig.width=15, fig.height=6, echo=FALSE}
for (col in 4:ncol(df)) {
  if (col == 4) {
    boxplot(df[,col] ~ df[,"Áreas"] * df[,"Prof"] * df[,"Coleta"], main=paste(names(df)[col]),las=2,xlab="")
    print(paste(names(df)[col]))
    
    print(kruskal.test(df[,col]~df[,"Áreas"]))
    
    if(kruskal.test(df[,col]~df[,"Áreas"])$p.value < 0.05) {
      dunn.test(df[,col],df["Áreas"])
    }
    
    print(kruskal.test(df[,col]~df[,"Prof"]))
    if(kruskal.test(df[,col]~df[,"Prof"])$p.value < 0.05) {
      dunn.test(df[,col],df["Prof"])
    }
    
    print(kruskal.test(df[,col]~df[,"Coleta"]))
    if(kruskal.test(df[,col]~df[,"Coleta"])$p.value < 0.05) {
      dunn.test(df[,col],df["Coleta"])
    }
    
    print(wilcox.test(df[,col]~df[,"Prof"]))
    print(wilcox.test(df[,col]~df[,"Coleta"]))
    #print(GFD(df[,col] ~ df[,"Áreas"] * df[,"Prof"] * df[,"Coleta"]))
  } else {
    boxplot(df[,col] ~ df[,"Áreas"] * df[,"Prof"], main=paste(names(df)[col]))
    print(paste(names(df)[col]))
    
    print(kruskal.test(df[,col]~df[,"Áreas"]))
    if(kruskal.test(df[,col]~df[,"Áreas"])$p.value < 0.05) {
      dunn.test(df[,col],df[,"Áreas"])
    }
    print(kruskal.test(df[,col]~df[,"Prof"]))
    if (kruskal.test(df[,col]~df[,"Prof"])$p.value < 0.05){
      dunn.test(df[,col],df[,"Prof"])
    }
    print(wilcox.test(df[,col]~df[,"Prof"]))

    #print(GFD(df[,col][1:24] ~ df[,"Áreas"][1:24] * df[,"Prof"][1:24]))
  }
}
```

